// nml-ui-copilot/src/components/Navbar.tsx
import { Link, useNavigate } from 'react-router-dom';
import { useAppDispatch, useAppSelector } from '../store/hooks';
import { logout } from '../store/authSlice';
import { Button } from './ui/Button';
import { Shield, User, ShoppingBag, Map, BookOpen, LogOut } from 'lucide-react';

export default function Navbar() {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const { user, isAuthenticated } = useAppSelector((state) => state.auth);

  const handleLogout = async () => {
    await dispatch(logout());
    navigate('/login');
  };

  if (!isAuthenticated) {
    return null;
  }

  return (
    <nav className="bg-card border-b border-border sticky top-0 z-50 shadow-lg">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between h-16">
          <div className="flex items-center space-x-8">
            <Link to="/" className="flex items-center space-x-2">
              <Shield className="h-8 w-8 text-primary" />
              <span className="text-2xl font-bold bg-gradient-to-r from-primary to-blue-400 bg-clip-text text-transparent">
                NML Online
              </span>
            </Link>

            <div className="hidden md:flex space-x-4">
              <Link to="/carte">
                <Button variant="ghost" className="flex items-center space-x-2">
                  <Map className="h-5 w-5" />
                  <span>Carte</span>
                </Button>
              </Link>

              <Link to="/joueur">
                <Button variant="ghost" className="flex items-center space-x-2">
                  <User className="h-5 w-5" />
                  <span>Mon Joueur</span>
                </Button>
              </Link>

              <Link to="/boutique">
                <Button variant="ghost" className="flex items-center space-x-2">
                  <ShoppingBag className="h-5 w-5" />
                  <span>Boutique</span>
                </Button>
              </Link>

              <Link to="/regles">
                <Button variant="ghost" className="flex items-center space-x-2">
                  <BookOpen className="h-5 w-5" />
                  <span>Règles</span>
                </Button>
              </Link>
            </div>
          </div>

          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-2 px-3 py-1 bg-secondary rounded-lg">
              <User className="h-4 w-4 text-primary" />
              <span className="text-sm font-semibold">{user?.username}</span>
            </div>

            <Button
              variant="outline"
              size="sm"
              onClick={handleLogout}
              className="flex items-center space-x-2"
            >
              <LogOut className="h-4 w-4" />
              <span className="hidden sm:inline">Déconnexion</span>
            </Button>
          </div>
        </div>
      </div>
    </nav>
  );
}

// nml-ui-angular/src/app/components/navbar/navbar.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {
  mobileMenuOpen = signal(false);

  constructor(
    public authService: AuthService,
    private router: Router
  ) {}

  toggleMobileMenu(): void {
    this.mobileMenuOpen.update(state => !state);
  }

  closeMobileMenu(): void {
    this.mobileMenuOpen.set(false);
  }

  getUserInitial(): string {
    const username = this.authService.currentUser()?.username;
    return username ? username.charAt(0).toUpperCase() : '?';
  }

  logout(): void {
    this.authService.logout().subscribe(() => {
      this.closeMobileMenu();
      this.router.navigate(['/']);
    });
  }

  goToLogin(): void {
    this.closeMobileMenu();
    this.router.navigate(['/login']);
  }

  handleLogout(): void {
    this.logout();
  }
}


<nav class="bg-gradient-to-r from-military-dark via-military-base to-military-dark border-b border-hud-blue/30 sticky top-0 z-50 backdrop-blur-sm">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-20">
      <!-- Logo / Brand -->
      <a routerLink="/" class="flex items-center gap-3 group">
        <div class="relative">
          <div class="absolute inset-0 bg-hud-blue blur-md opacity-50 group-hover:opacity-75 transition-opacity"></div>
          <span class="relative text-4xl">🎯</span>
        </div>
        <div class="flex flex-col">
          <span class="font-military text-2xl font-bold text-hud-blue tracking-wider uppercase">NML</span>
          <span class="font-tactical text-xs text-gray-400 tracking-widest">TACTICAL OPS</span>
        </div>
      </a>

      <!-- Navigation Menu -->
      <div class="hidden md:flex items-center gap-1">
        <a routerLink="/carte" routerLinkActive="nav-active"
           class="nav-link flex items-center gap-2 px-4 py-2 rounded-md font-semibold uppercase tracking-wider text-sm transition-all hover:bg-military-lighter hover:text-hud-blue group">
          <span class="text-lg group-hover:scale-110 transition-transform">🗺️</span>
          <span>Carte</span>
        </a>
        <a routerLink="/joueur" routerLinkActive="nav-active"
           class="nav-link flex items-center gap-2 px-4 py-2 rounded-md font-semibold uppercase tracking-wider text-sm transition-all hover:bg-military-lighter hover:text-hud-blue group">
          <span class="text-lg group-hover:scale-110 transition-transform">👤</span>
          <span>Profil</span>
        </a>
        <a routerLink="/boutique" routerLinkActive="nav-active"
           class="nav-link flex items-center gap-2 px-4 py-2 rounded-md font-semibold uppercase tracking-wider text-sm transition-all hover:bg-military-lighter hover:text-hud-blue group">
          <span class="text-lg group-hover:scale-110 transition-transform">🛒</span>
          <span>Boutique</span>
        </a>
        <a routerLink="/regles" routerLinkActive="nav-active"
           class="nav-link flex items-center gap-2 px-4 py-2 rounded-md font-semibold uppercase tracking-wider text-sm transition-all hover:bg-military-lighter hover:text-hud-blue group">
          <span class="text-lg group-hover:scale-110 transition-transform">📖</span>
          <span>Règles</span>
        </a>
      </div>

      <!-- User Section -->
      <div class="flex items-center gap-3">
        @if (authService.isAuthenticated()) {
          <div class="hidden sm:flex items-center gap-3 px-4 py-2 bg-military-lighter rounded-md border border-hud-blue/20">
            <div class="w-10 h-10 rounded-full bg-gradient-to-br from-hud-blue to-hud-teal flex items-center justify-center font-bold text-military-dark">
              {{ getUserInitial() }}
            </div>
            <div class="flex flex-col">
              <span class="font-tactical text-xs text-gray-400 uppercase">Opérateur</span>
              <span class="font-semibold text-hud-blue">{{ authService.currentUser()?.username }}</span>
            </div>
          </div>
          <button (click)="logout()"
                  class="px-4 py-2 bg-warning-red hover:bg-warning-red/80 text-white font-semibold uppercase tracking-wider text-sm rounded-md transition-all clip-corner flex items-center gap-2">
            <span>🚪</span>
            <span class="hidden sm:inline">Déconnexion</span>
          </button>
        } @else {
          <button (click)="goToLogin()"
                  class="px-6 py-2 bg-gradient-to-r from-hud-blue to-hud-teal text-military-dark font-bold uppercase tracking-wider text-sm rounded-md transition-all hover:shadow-tactical clip-corner">
            Connexion
          </button>
        }
      </div>
    </div>
  </div>
</nav>
